server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: auction-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auction-service
          __path__: /logs/auction-service/*.log

  - job_name: identify-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: identify-service
          __path__: /logs/identify-service/*.log
